name: React CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint --if-present

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

      - name: Upload production-ready build
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build
